import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PremiumNav } from '@/components/premium-nav';

const answers=[{label:'A Fish',correct:false},{label:'A Turtle',correct:true},{label:'A Dolphin',correct:false}];
const cards=[['🍎','Word Match','Une palabras'],['🐯','Find the Picture','Encuentra la imagen'],['🎧','Listen & Choose','Escucha y elige'],['🧩','Puzzle','Arma la imagen'],['🃏','Memory','Memoria'],['🔤','Build the Word','Forma la palabra'],['🎤','Pronunciation','Habla y gana'],['🌍','World Quest','Explora culturas']];
export default function GamesScreen(){
 const [selected,setSelected]=useState<string|null>(null);const result=useMemo(()=>answers.find(i=>i.label===selected),[selected]);
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><PremiumNav/>
  <View style={styles.header}><View><Text style={styles.eyebrow}>APRENDE JUGANDO</Text><Text style={styles.title}>Juegos</Text><Text style={styles.sub}>Retos visuales, memoria, escucha y pronunciación.</Text></View><View style={styles.points}><Text style={styles.pointsText}>⭐ 27</Text></View></View>
  <View style={styles.categoryRow}>{['Todos','Vocabulario','Memoria','Pronunciación','Gramática'].map((x,i)=><View key={x} style={[styles.category,i===0&&styles.categoryActive]}><Text style={[styles.categoryText,i===0&&styles.categoryTextActive]}>{x}</Text></View>)}</View>
  <View style={styles.grid}>{cards.map(([icon,title,caption],i)=><View key={title} style={[styles.gameCard,{backgroundColor:['#FFF','#F8F0FF','#EFF8FF','#FFF7E7'][i%4]}]}><Text style={styles.gameIcon}>{icon}</Text><Text style={styles.gameTitle}>{title}</Text><Text style={styles.gameCaption}>{caption}</Text><View style={styles.xpBadge}><Text style={styles.xpText}>+10 XP</Text></View></View>)}</View>
  <View style={styles.challenge}><View style={styles.challengeVisual}><Text style={styles.turtle}>🐢</Text><Text style={styles.sparkles}>✨🌊✨</Text></View><View style={styles.challengeContent}><Text style={styles.challengeLabel}>RETO DEL DÍA</Text><Text style={styles.challengeTitle}>What animal is this?</Text><Text style={styles.challengeSub}>Escoge la respuesta correcta</Text><View style={styles.answerList}>{answers.map(a=>{const active=selected===a.label;const good=active&&a.correct;const bad=active&&!a.correct;return <Pressable key={a.label} onPress={()=>setSelected(a.label)} style={[styles.answer,good&&styles.good,bad&&styles.bad]}><Text style={[styles.answerText,good&&styles.goodText,bad&&styles.badText]}>{a.label} {good?'✓':bad?'↻':''}</Text></Pressable>})}</View>{result&&<View style={[styles.feedback,result.correct?styles.feedbackGood:styles.feedbackTry]}><Text style={styles.feedbackTitle}>{result.correct?'🎉 Excellent!':'💪 Almost!'}</Text><Text style={styles.feedbackText}>{result.correct?'Turtle significa tortuga. +1 estrella.':'Mira la imagen y vuelve a intentarlo.'}</Text></View>}</View></View>
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#EAF7FF'},page:{padding:14,gap:14,maxWidth:1200,width:'100%',alignSelf:'center'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:'#FFF',borderRadius:24,padding:18,borderWidth:1,borderColor:'#D8E9FF'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#7C49FF'},title:{fontSize:31,fontWeight:'900',color:'#173C78'},sub:{color:'#687B9A',marginTop:3},points:{backgroundColor:'#FFF4D8',paddingVertical:9,paddingHorizontal:14,borderRadius:16},pointsText:{fontWeight:'900',color:'#9B6A00'},categoryRow:{flexDirection:'row',flexWrap:'wrap',gap:8},category:{backgroundColor:'#FFF',borderRadius:15,paddingVertical:9,paddingHorizontal:14,borderWidth:1,borderColor:'#DCEAFF'},categoryActive:{backgroundColor:'#7C49FF'},categoryText:{color:'#315A92',fontWeight:'800',fontSize:12},categoryTextActive:{color:'#FFF'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},gameCard:{flexGrow:1,flexBasis:180,minWidth:155,borderRadius:22,padding:17,borderWidth:1,borderColor:'#DDEAFF',position:'relative'},gameIcon:{fontSize:38},gameTitle:{marginTop:8,fontWeight:'900',color:'#173C78',fontSize:15},gameCaption:{marginTop:3,color:'#6D7E99',fontSize:12},xpBadge:{position:'absolute',right:10,top:10,backgroundColor:'#EAF9F1',paddingHorizontal:8,paddingVertical:4,borderRadius:11},xpText:{fontSize:9,fontWeight:'900',color:'#1C9256'},challenge:{flexDirection:'row',flexWrap:'wrap',gap:14,backgroundColor:'#DDF5FF',borderRadius:28,padding:18,borderWidth:1,borderColor:'#CBE8FF'},challengeVisual:{flex:1,minWidth:230,alignItems:'center',justifyContent:'center',backgroundColor:'#EAFBFF',borderRadius:22,padding:20},turtle:{fontSize:110},sparkles:{fontSize:25},challengeContent:{flex:1,minWidth:260},challengeLabel:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#7C49FF'},challengeTitle:{fontSize:27,fontWeight:'900',color:'#173C78',marginTop:4},challengeSub:{color:'#647899',marginTop:3},answerList:{gap:8,marginTop:14},answer:{backgroundColor:'#FFF',borderRadius:16,padding:13,borderWidth:2,borderColor:'#DDEAFF'},good:{backgroundColor:'#E9FFF2',borderColor:'#26C777'},bad:{backgroundColor:'#FFF0F4',borderColor:'#FF6A9F'},answerText:{fontWeight:'900',color:'#274D84',textAlign:'center'},goodText:{color:'#188D52'},badText:{color:'#C54D72'},feedback:{marginTop:10,borderRadius:16,padding:13},feedbackGood:{backgroundColor:'#E8FFF1'},feedbackTry:{backgroundColor:'#FFF4D8'},feedbackTitle:{fontWeight:'900',color:'#173C78'},feedbackText:{marginTop:3,color:'#5C7190'}})
