import { Link } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PremiumNav } from '@/components/premium-nav';
import { languageOptions } from '@/data/languages';

const gamePreview=[
 ['🍎','Word Match'],['🎧','Listen & Choose'],['🧩','Puzzle'],['🃏','Memory'],['🎤','Pronunciation'],['🌍','World Quest'],
] as const;

export default function HomeScreen(){
 const {width}=useWindowDimensions();
 const wide=width>=980;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><PremiumNav/>
   <View style={StyleSheet.flatten([styles.hero,wide?styles.heroWide:null])}>
     <View style={styles.child}><Text style={styles.childFace}>👧🏼</Text><Text style={styles.alanaTag}>Alana</Text></View>
     <View style={styles.heroCenter}><View style={styles.logo}><Text style={styles.alana}>Alana</Text><Text style={styles.heart}>♥</Text><Text style={styles.victoria}>Victoria</Text></View><Text style={styles.languages}>L A N G U A G E S</Text><Text style={styles.slogan}>Pequeños hoy, grandes mañana.</Text><Text style={styles.heroText}>Aprende idiomas con juegos, voz, Teacher AI y actividades creadas para cada edad.</Text><View style={styles.ctaRow}><Link href="/language/en" asChild><Pressable style={styles.cta}><Text style={styles.ctaText}>▶ COMENZAR AHORA</Text></Pressable></Link><Link href="/search" asChild><Pressable style={styles.searchBtn}><Text style={styles.searchBtnText}>⌕ Buscar</Text></Pressable></Link></View></View>
     <View style={styles.child}><Text style={styles.childFace}>👧🏻</Text><Text style={styles.victoriaTag}>Victoria</Text></View>
   </View>

   <View style={styles.languageStrip}>{languageOptions.map(lang=><Link key={lang.code} href={`/language/${lang.code}`} asChild><Pressable style={styles.languageChip}><Text style={styles.flag}>{lang.flag}</Text><Text style={styles.languageName}>{lang.nativeName}</Text><Text style={styles.open}>→</Text></Pressable></Link>)}</View>

   <View style={StyleSheet.flatten([styles.row,!wide?styles.stack:null])}>
     <View style={styles.lessonCard}><Text style={styles.kicker}>CONTINÚA APRENDIENDO</Text><Text style={styles.cardTitle}>🌺 Hawaii Lesson</Text><Text style={styles.phrase}>Good morning, everyone!</Text><Text style={styles.translation}>¡Buenos días a todos!</Text><View style={styles.smallRow}><Link href="/lesson" asChild><Pressable style={styles.blueBtn}><Text style={styles.btnText}>🔊 Escuchar</Text></Pressable></Link><Link href="/pronunciation" asChild><Pressable style={styles.pinkBtn}><Text style={styles.btnText}>🎤 Tu turno</Text></Pressable></Link></View></View>
     <View style={styles.scoreCard}><Text style={styles.scoreTitle}>¡Excelente!</Text><Text style={styles.stars}>★★★</Text><Text style={styles.percent}>94%</Text><Text style={styles.muted}>Último resultado de pronunciación</Text><Link href="/progress" asChild><Pressable style={styles.softBtn}><Text style={styles.softText}>Ver progreso →</Text></Pressable></Link></View>
     <View style={styles.gamesCard}><Text style={styles.cardTitle}>🎮 Juegos</Text><Text style={styles.muted}>24 actividades disponibles</Text><View style={styles.gameGrid}>{gamePreview.map(([icon,name])=><Link key={name} href="/games" asChild><Pressable style={styles.game}><Text style={styles.gameIcon}>{icon}</Text><Text style={styles.gameText}>{name}</Text></Pressable></Link>)}</View><Link href="/games" asChild><Pressable style={styles.softBtn}><Text style={styles.softText}>Ver todos los juegos →</Text></Pressable></Link></View>
   </View>

   <View style={StyleSheet.flatten([styles.row,!wide?styles.stack:null])}>
     <Link href="/teacher" asChild><Pressable style={styles.feature}><Text style={styles.featureIcon}>🤖</Text><View style={styles.featureCopy}><Text style={styles.featureTitle}>Teacher AI</Text><Text style={styles.featureText}>Practica, pregunta, conversa y recibe retos.</Text></View><Text style={styles.featureArrow}>→</Text></Pressable></Link>
     <Link href="/scan" asChild><Pressable style={styles.featureWarm}><Text style={styles.featureIcon}>📸</Text><View style={styles.featureCopy}><Text style={styles.featureTitle}>Mi Tarea</Text><Text style={styles.featureText}>Sube una foto y conviértela en una lección.</Text></View><Text style={styles.featureArrow}>→</Text></Pressable></Link>
     <Link href="/progress" asChild><Pressable style={styles.featurePurple}><Text style={styles.featureIcon}>📈</Text><View style={styles.featureCopy}><Text style={styles.featureTitle}>Mi Progreso</Text><Text style={styles.featureText}>XP, estrellas, rachas, insignias y niveles.</Text></View><Text style={styles.featureArrow}>→</Text></Pressable></Link>
   </View>

   <View style={styles.footer}><Text style={styles.footerTitle}>Confident kids. A brighter tomorrow. ♥</Text><Text style={styles.footerText}>Web · Android · iOS · Tablet · Smart TV</Text></View>
 </ScrollView></SafeAreaView>
}

const styles=StyleSheet.create({
 safe:{flex:1,backgroundColor:'#EAF7FF'},page:{padding:14,gap:14,maxWidth:1500,width:'100%',alignSelf:'center'},
 hero:{backgroundColor:'#CFEFFF',borderRadius:30,padding:20,borderWidth:1,borderColor:'#B9E4FF',alignItems:'center',gap:16,overflow:'hidden'},heroWide:{flexDirection:'row',justifyContent:'space-between'},child:{alignItems:'center',minWidth:170},childFace:{fontSize:100},alanaTag:{backgroundColor:'#FF58A7',color:'#FFF',fontWeight:'900',paddingVertical:7,paddingHorizontal:20,borderRadius:18,marginTop:-8},victoriaTag:{backgroundColor:'#7A46FF',color:'#FFF',fontWeight:'900',paddingVertical:7,paddingHorizontal:20,borderRadius:18,marginTop:-8},heroCenter:{flex:1,alignItems:'center'},logo:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',justifyContent:'center'},alana:{fontSize:42,fontWeight:'900',color:'#FF2F98'},heart:{fontSize:30,color:'#FF2F98',marginHorizontal:8},victoria:{fontSize:42,fontWeight:'900',color:'#743CFF'},languages:{fontSize:12,fontWeight:'900',letterSpacing:5,color:'#153F85'},slogan:{fontSize:24,fontWeight:'900',color:'#173C78',marginTop:8,textAlign:'center'},heroText:{color:'#5C7397',textAlign:'center',marginTop:5,maxWidth:560,lineHeight:20},ctaRow:{flexDirection:'row',gap:9,marginTop:14,flexWrap:'wrap',justifyContent:'center'},cta:{backgroundColor:'#FF2F98',borderRadius:20,paddingVertical:14,paddingHorizontal:24},ctaText:{color:'#FFF',fontWeight:'900'},searchBtn:{backgroundColor:'#FFF',borderRadius:20,paddingVertical:14,paddingHorizontal:20,borderWidth:1,borderColor:'#D5E7FF'},searchBtnText:{color:'#264D83',fontWeight:'900'},
 languageStrip:{flexDirection:'row',flexWrap:'wrap',gap:8,backgroundColor:'#FFF',borderRadius:24,padding:10,borderWidth:1,borderColor:'#DCEAFF'},languageChip:{flexGrow:1,minWidth:120,flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'#F8FBFF',borderRadius:18,padding:11,borderWidth:1,borderColor:'#E2ECFF'},flag:{fontSize:25},languageName:{flex:1,fontSize:12,fontWeight:'900',color:'#173C78'},open:{fontWeight:'900',color:'#7B46FF'},
 row:{flexDirection:'row',gap:12,alignItems:'stretch'},stack:{flexDirection:'column'},lessonCard:{flex:1,backgroundColor:'#DDF5FF',borderRadius:25,padding:18,borderWidth:1,borderColor:'#CBE8FF'},scoreCard:{flex:1,backgroundColor:'#EEFFF4',borderRadius:25,padding:18,borderWidth:1,borderColor:'#D4F4DF',alignItems:'center'},gamesCard:{flex:1,backgroundColor:'#FFF1F6',borderRadius:25,padding:18,borderWidth:1,borderColor:'#FFD8E7'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#7B46FF'},cardTitle:{fontSize:21,fontWeight:'900',color:'#173C78',marginTop:4},phrase:{fontSize:22,fontWeight:'900',color:'#173C78',marginTop:15},translation:{color:'#607A97',marginTop:3},smallRow:{flexDirection:'row',gap:8,marginTop:15},blueBtn:{flex:1,backgroundColor:'#13A7FF',borderRadius:16,padding:12,alignItems:'center'},pinkBtn:{flex:1,backgroundColor:'#FF2F98',borderRadius:16,padding:12,alignItems:'center'},btnText:{color:'#FFF',fontWeight:'900'},scoreTitle:{fontSize:22,fontWeight:'900',color:'#20A859'},stars:{fontSize:38,color:'#FFB400',letterSpacing:3,marginTop:5},percent:{fontSize:35,fontWeight:'900',color:'#173C78'},muted:{color:'#6B7E99',fontSize:12,marginTop:3},softBtn:{marginTop:14,backgroundColor:'#E7F1FF',borderRadius:16,padding:11,alignItems:'center'},softText:{fontWeight:'900',color:'#25528D'},gameGrid:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:12},game:{flexGrow:1,flexBasis:90,minWidth:85,backgroundColor:'#FFF',borderRadius:15,padding:9,alignItems:'center'},gameIcon:{fontSize:25},gameText:{fontSize:9,fontWeight:'900',color:'#294F84',textAlign:'center',marginTop:3},
 feature:{flex:1,minWidth:230,backgroundColor:'#E5F6FF',borderRadius:24,padding:17,flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:'#CDEBFF'},featureWarm:{flex:1,minWidth:230,backgroundColor:'#FFF5D9',borderRadius:24,padding:17,flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:'#FFE7AA'},featurePurple:{flex:1,minWidth:230,backgroundColor:'#F1EAFF',borderRadius:24,padding:17,flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:'#DFD1FF'},featureIcon:{fontSize:42},featureCopy:{flex:1},featureTitle:{fontSize:18,fontWeight:'900',color:'#173C78'},featureText:{fontSize:12,color:'#607A97',marginTop:3,lineHeight:17},featureArrow:{fontSize:25,fontWeight:'900',color:'#7B46FF'},
 footer:{backgroundColor:'#FFF',borderRadius:22,padding:18,alignItems:'center',borderWidth:1,borderColor:'#DCEAFF'},footerTitle:{fontSize:17,fontWeight:'900',color:'#173C78',textAlign:'center'},footerText:{color:'#7586A0',marginTop:4,fontSize:12}
});
